replicaCount: 1

image:
  repository: hotio/readarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - readarr.smrtrock.com
  tls:
   - secretName: readarr-smrtrock-com
     hosts:
       - readarr.smrtrock.com

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/config"
    subPath: "configs/readarr"
  - name: myvolume
    mountPath: "/downloads/deluge"
    subPath: "downloads/deluge"
  - name: myvolume
    mountPath: "/downloads/nzbget"
    subPath: "downloads/nzbget"
  - name: myvolume
    mountPath: "/books"
    subPath: "medias/books"

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 256Mi
    cpu: 0.5

nodeSelector: {}

tolerations: []

affinity: {}