apiVersion: v1
kind: Service
metadata:
  name: {{ template "deluge.fullname" . }}-webui
  labels:
    app.kubernetes.io/name: {{ include "deluge.name" . }}
    helm.sh/chart: {{ include "deluge.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.webuiservice.labels }}
{{ toYaml .Values.webuiservice.labels | indent 4 }}
{{- end }}
{{- with .Values.webuiservice.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.webuiservice.type "ClusterIP") (empty .Values.webuiservice.type)) }}
  type: ClusterIP
  {{- if .Values.webuiservice.clusterIP }}
  clusterIP: {{ .Values.webuiservice.clusterIP }}
  {{end}}
{{- else if eq .Values.webuiservice.type "LoadBalancer" }}
  type: {{ .Values.webuiservice.type }}
  {{- if .Values.webuiservice.loadBalancerIP }}
  loadBalancerIP: {{ .Values.webuiservice.loadBalancerIP }}
  {{- end }}
  {{- if .Values.webuiservice.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.webuiservice.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.webuiservice.type }}
{{- end }}
{{- if .Values.webuiservice.externalIPs }}
  externalIPs:
{{ toYaml .Values.webuiservice.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.webuiservice.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.webuiservice.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.webuiservice.port }}
      protocol: TCP
      targetPort: http
{{ if (and (eq .Values.webuiservice.type "NodePort") (not (empty .Values.webuiservice.nodePort))) }}
      nodePort: {{.Values.webuiservice.nodePort}}
{{ end }}
  selector:
    app.kubernetes.io/name: {{ include "deluge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}